// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200304115534_Muse")]
    partial class Muse
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Domain.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nico Yazawa"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Maki Nishikino"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Eli Ayase"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Honoka Kosaka"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kotori Minami"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hanayo Koizumi"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Umi Sonoda"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Rin Hoshizora"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Nozomi Tojo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
