// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200308131559_AllIdolCharacters")]
    partial class AllIdolCharacters
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Domain.IdolCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BustSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HipsSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameDefault")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEng")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameJp")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeiyuuEng")
                        .HasColumnType("TEXT");

                    b.Property<string>("SeiyuuJp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subunit")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurnameEng")
                        .HasColumnType("TEXT");

                    b.Property<string>("SurnameJp")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WaistSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearOfSchoool")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("IdolCharacters");
                });

            modelBuilder.Entity("Domain.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nico Yazawa"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Maki Nishikino"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Eli Ayase"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Honoka Kosaka"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Kotori Minami"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hanayo Koizumi"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Umi Sonoda"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Rin Hoshizora"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Nozomi Tojo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
